// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fecxbzrtjoluggdaudvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlY3hienJ0am9sdWdnZGF1ZHZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2NDQzNzMsImV4cCI6MjA3NTIyMDM3M30.yEWLOZxvB2TE0WOYUFLs_sHnErLUAu753ivZhp0-u2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});